"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class gripper_command_t(object):

    __slots__ = ["open"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.open = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(gripper_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.open))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gripper_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gripper_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = gripper_command_t()
        self.open = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if gripper_command_t in parents: return 0
        tmphash = (0xf5f784b462c6d1f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if gripper_command_t._packed_fingerprint is None:
            gripper_command_t._packed_fingerprint = struct.pack(">Q", gripper_command_t._get_hash_recursive([]))
        return gripper_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", gripper_command_t._get_packed_fingerprint())[0]

